### ISSUE TITLE
Missing no data on SLD

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#1]
SLD generated by QGIS has no data value for transparency
For PROB.sld the example is:

` <sld:ColorMapEntry color="#FFFFFF" label="NODATA" opacity="0.0" quantity="255"/>
`

**Comment by thengl** [comment]
I've added those consistently to all SLD files. See e.g.: https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/aggregated/BLDFIE.sld
