### ISSUE TITLE
access to geoserver @164.132.26.91 MAC: 02:00:00:3C:19:81

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#14]
The server 164.132.26.91 contains the current version of soilgrid250m
http://164.132.26.91:8080/geoserver/web/

**login geoserver**
login:admin and root
pwd: ?s5tu7Q!

** login ssh **
login: isric
pwd: yhg34@1Q

The current soilgrids250m layers are being pulled from this is a copy from the content in server since I had to do modifications to the file system
/media/sf_sg250m_geoserver

This is a vboxsf mount therefore you need to be root and/or tomcat7 user. To avoid problems with the filesystem upload directly to /media/sf_sg250m_geoserver on a slow internet connection, to much speed with damage the raid6

If the file system gets corrupted the VMs need to be rebooted (contact Eloi: eloi.carvalhoribeiro@wur.nl).

**Comment by milankili** [comment]
http://164.132.26.91:8080/geoserver/geonode/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode:cecsol_m_sl4_250m,geonode:cecsol_m_sl4_250m&styles=values,&bbox=-180.0,-62.00080943400002,179.9999424,87.37&width=768&height=330&srs=EPSG:4326&format=application/openlayers

**Comment by jorgejesus** [comment]
Server is now using the new standard domain
http://webservices.isric.org/geoserver
e.g
http://webservices.isric.org/geoserver/geonode/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode:cecsol_m_sl4_250m,geonode:cecsol_m_sl4_250m&styles=values,&bbox=-180.0,-62.00080943400002,179.9999424,87.37&width=768&height=330&srs=EPSG:4326&format=application/openlayers

**Comment by jorgejesus** [comment]
For the numeric

**Comment by jorgejesus** [comment]
Current redirects:
af.soilgrids.org 	--> http://85.214.135.140/AfSISMaster/dist
af250mt.soilgrids.org --> http://85.214.135.140/AfSISMaster/dist

New redirects
af.soilgrids.org 	--> http://dev.soilgrids.org/#/?lon=23.115234375000004&lat=3.732

af250mt.soilgrids.org --> http://dev.soilgrids.org....
