### ISSUE TITLE
White/Color stripe around Japan

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#16]
There is a color change around Japan at high zoom. The transparency request of WMS is not respected:
E.g:
http://webservices.isric.org/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Ataxnwrb_250m&CRS=EPSG%3A3857&WIDTH=256&HEIGHT=256&STYLES=&BBOX=15028131.257091936%2C-5009377.085697312%2C20037508.342789248%2C-9.313225746154785e-10

and 
http://webservices.isric.org/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=false&LAYERS=geonode%3Ataxnwrb_250m&CRS=EPSG%3A3857&WIDTH=256&HEIGHT=256&STYLES=&BBOX=15028131.257091936%2C-5009377.085697312%2C20037508.342789248%2C-9.313225746154785e-10

Give PNG with white background.

Logs report no errors and everything is OK with JAI and other system. The problem is caused by web mercator projection, the same request with 4326 respects transparency

http://webservices.isric.org/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3A_TAXNWRB_250m&CRS=EPSG%3A4326&WIDTH=256&HEIGHT=256&STYLES=&BBOX=-40.9798980696,135,0,180

Possible solution: Change OL3 View to 4326?

**Comment by aL3xa** [comment]
I tried changing projection to `EPSG:4326` only for raster layer, but it didn't work. I reckon I have to change it for the other layers as well. Anyhow, this by far transcends my geo mapping skills, so I'll leave it for tomorrow when I meet with @milankili and @thengl

**Comment by jorgejesus** [comment]
Moved to soilgrids.org private repository
