### ISSUE TITLE
Move soilgrids.org to OVH control panel

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#19]
To avoid overloading the isric.org server it is better that all soilgrids is run on the OVH server.

1) Request soilgrids2.org on OVH
2) Test system with soilgrids2.org
3) Move soilgrids.org from STRATO to OVH

**Comment by thengl** [comment]
Jorge, please no soilgrids2 domain. Make a copy of everything on OVH and then transfer the domain to new server. As long as it can be done in <48hrs is fine is we go offline.
On 28 Jun 2016 09:08, Jorge Samuel Mendes de Jesus <notifications@github.com> wrote:To avoid overloading the isric.org server it is better that all soilgrids is run on the OVH server.

1) Request soilgrids2.org on OVH
2) Test system with soilgrids2.org
3) Move soilgrids.org from STRATO to OVH

**Comment by jorgejesus** [comment]
I prefer to test the redirects and reverse proxy with a temporary domain, when that work is complete then it is safe to move the soilgrids.org to OVH.

Lets make it clear the soilgrids2.org or soilgrids.ovh is just to help me and will be never used in production

**Comment by thengl** [comment]
OK, then use "soilgrids.ovh"
In future, please try to avoid soilgrids2, soilinfo2 etc. I can explain 
you why (usually it confuses people because they think that these are 
version 2).


On 28/06/16 13:26, Jorge Samuel Mendes de Jesus wrote:
> I prefer to test the redirects and reverse proxy with a temporary
> domain, when that work is complete then it is safe to move the
> soilgrids.org to OVH.
>
> Lets make it clear the soilgrids2.org or soilgrids.ovh is just to help
> me and will be never used in production
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ISRICWorldSoil/SoilGrids250m/issues/19#issuecomment-229022650>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAnG0mtKF6duMbNS3BchI7dReSiK-kGLks5qQQT-gaJpZM4I_zcq>.
>

-- 
T. (Tom) Hengl
Researcher @ ISRIC - World Soil Information
Team member Africa Soil Information Services http://africasoils.net
Url: http://www.wageningenur.nl/en/Persons/dr.-T-Tom-Hengl.htm
Network: http://profiles.google.com/tom.hengl
Publications: http://scholar.google.com/citations?user=2oYU7S8AAAAJ

**Comment by jorgejesus** [comment]
Anonymous FTP available on temporary:
ftp://ftp.soilgrids.ovh
Current soilgrids FTP is being mirrored

**Comment by jorgejesus** [comment]
Anonymous + soilgrids:soilgrids @ ftp.soilgrids.ovh  
- Chroot active for soilgrids
- SSH access or group ftp blocked

**Comment by jorgejesus** [comment]
DNS+EngineX redirect is working properly eg:
af.soilgrids.ovh --> dev.soilgrids.org
dev-rest.soilgrids.ovh --> dev-rest.soilgrids.org

**Comment by jorgejesus** [comment]
http://rest.soilgrids.ovh is not ok with domain changes.
Will wait for official release to make redirects and close all old soilgrids
