### ISSUE TITLE
Derive confusion matrices for USDA and WRB classification for higher level classes

### ISSUE THREAD

**Issue by thengl** [ISRICWorldSoil/SoilGrids250m#20]
Derive confusion matrices for USDA and WRB classification for higher level classes so that we can compare with lower level accuracy. The assumption is that the accuracy for the higher level (orders for USDA, groups for WRB) should be slightly better than for lower level.

**Comment by mruiperez** [comment]
Close  #20

**Comment by mruiperez** [comment]
closes #20
