### ISSUE TITLE
Jump in clay values across USA-Mexico border (possible bug)

### ISSUE THREAD

**Issue by thengl** [ISRICWorldSoil/SoilGrids250m#25]
Laurent Courty has discovered that there is now a jump in clay values from USA to Mexico:

![soilgrids_clay_sl1_250m](https://cloud.githubusercontent.com/assets/640722/18415942/b14b49dc-7804-11e6-8efc-56711ec81884.png)

This jump was not previously visible in the 1km version of SoilGrids:

![soilgrids_clay_sl1_1km](https://cloud.githubusercontent.com/assets/640722/18415944/b7c39602-7804-11e6-87f9-039c0f60a909.png)

It could be that there was an error in import of new soil profiles obtained from INEGI/CONABIO institutes (see [import functions](https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/profiles/INEGI/rw_MXSPD.R)) or this happened as affect of artifacts in e.g. lithological map? Needs to be validated / checked.

**Comment by lrntct** [comment]
Thanks.
It could be noted that in addition to Mexico, the clay value of most of Central America and Caribbean is much higher in the 250m version than in the 1km version. E.G there is no jump in value between Guatemala or Belize and Mexico.

**Comment by thengl** [comment]
It is a bug: in the [line 71](https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/profiles/INEGI/rw_MXSPD.R) currently stands:
- "ARCILLA"="SNDPPT","LIMO"="SLTPPT","ARENA"="CLYPPT"

and should be
- "ARCILLA"="CLYPPT","LIMO"="SLTPPT","ARENA"="SNDPPT"

**Comment by marioguevara** [comment]
the bug starts in lines 59 and 60,  currently stands

"R"="SNDPPT","L"="SLTPPT","A"="CLYPPT") 

and should be

"R"="CLYPPT","L"="SLTPPT","A"="SNDPPT"

**Comment by thengl** [comment]
Now resolved. The updated maps can be downloaded from ftp://ftp.soilgrids.org/data/recent/

**Comment by lrntct** [comment]
The new dataset makes more sense but the clay value in Mexico is still noticeably higher than north of the border (here sl4/sd4):
![soilgrids_clay_sl1_250m_v2](https://cloud.githubusercontent.com/assets/12278765/25452830/9628c950-2a8c-11e7-8714-9d138c0eec8e.png)

And the 1km for reference:
![soilgrids_clay_sl1_1km_v2](https://cloud.githubusercontent.com/assets/12278765/25452829/95fde3d4-2a8c-11e7-93f0-6ec170d2f769.png)

**Comment by thengl** [comment]
Yes it could be a harmonization problem ( but it could also be that indeed clay values are higher). Need to sit down with Mario and chat about what is going on. Note we did not have the MX points for the 1km version of predictions.
