### ISSUE TITLE
Missing values around 180E / 180W

### ISSUE THREAD

**Issue by lrntct** [ISRICWorldSoil/SoilGrids250m#26]
There are missing values around the the parallel 180. I was first suspecting import problem in my GIS, but the gap could be seen on the web interface too.

![missingvalues180](https://cloud.githubusercontent.com/assets/12278765/18455146/d0ebf7a0-790d-11e6-9ef6-93635a4242b7.png)

![missingvalues180_russia](https://cloud.githubusercontent.com/assets/12278765/18455156/d6e751c2-790d-11e6-9b40-1c26177a8376.png)

**Comment by thengl** [comment]
Now resolved. The updated maps can be downloaded from ftp://ftp.soilgrids.org/data/recent/
