### ISSUE TITLE
missing class color in TAXNWRB and TAXOUSDA

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#3]
On TAXOUSDA.sld

 <ColorMapEntry color="NA" quantity="64" label="Xerands" opacity="0.7"/>

On TAXNGWRB.sld

 <ColorMapEntry color="NA" quantity="117" label="Vetic Acrisols" opacity="0.7"/>

**Comment by thengl** [comment]
Now fixed in https://github.com/ISRICWorldSoil/SoilGrids250m/commit/02a9de5a5d279e71de202746678d0c6064a7a737  all SLD files have been uploaded to copybara
