### ISSUE TITLE
REST 500 internal server error

### ISSUE THREAD

**Issue by Junobijlard** [ISRICWorldSoil/SoilGrids250m#32]
https://rest.soilgrids.org/ is showing a 500 internal server error, are there any issues?

**Comment by thengl** [comment]
There has been a bug in REST SoilGrids, but this has [now been resolved](https://groups.google.com/d/msg/global-soil-information/qp_QfS7ooZA/HZ4M8mEKBAAJ). We are transferring in the coming 2 weeks all services to a higher capacity server to prevent fallout's of the server.
