### ISSUE TITLE
Cannot request any data (for example chemical soil properties). Error: Unknown soil mask 

### ISSUE THREAD

**Issue by Najim88** [ISRICWorldSoil/SoilGrids250m#38]
I cannot request any data on any location. It keeps giving the error message Unknown soil mask.

**Comment by thengl** [comment]
Yes I see the problem. Basically the whole REST is down. Most likely issue with the new server / https setting.

**Comment by thengl** [comment]
REST is again operational from:

https://85.214.241.121/query?lon=27.7921875&lat=0.823547737882862

We just need to connect all domains again and everything should 100% up and running again.

**Comment by thengl** [comment]
REST has been now fixed. It is running on a new machine with more capacity and which should ensure faster speeds.

![3173908b-9c6f-4344-a493-4959be6b55e6](https://user-images.githubusercontent.com/640722/28155715-1f1f43f0-67b0-11e7-8aa7-f9e062285e2d.jpg)
