### ISSUE TITLE
Latitude and lognitude inverted when searching for location

### ISSUE THREAD

**Issue by thengl** [ISRICWorldSoil/SoilGrids250m#39]
Bas just discovered that in the search bar in SoilGrids.org Latitude and longitude are inverted as the result shows opposite coordinates:

![bug_lat_lon_coordinates_soilgrids](https://user-images.githubusercontent.com/640722/28156798-73f40146-67b4-11e7-9f79-4aab1cb42af4.png)

A little bug but let's try to fix is it a.s.a.p.

**Comment by Luka-G** [comment]
@thengl  https://dev.soilgrids.org
I've just switched E and N to get the right match. If this is ok, I will move it to the master?

**Comment by thengl** [comment]
Yes (note: adding to each master commit bug fix version highly recommended e.g. "0.5-1").
