### ISSUE TITLE
TAXOUSDA.sld has incorrect values

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#4]
TAXOUSDA.sld has ZERO for NODATA   the correct value is 255

` <ColorMapEntry color="#FFFFFF" quantity="1" label="NODATA" opacity="0.0"/>  `

Should be "Albolls"  ???  I think we have been using an incorrect TAXOUSDA for  af soilgrids

**Comment by thengl** [comment]
Now fixed in https://github.com/ISRICWorldSoil/SoilGrids250m/commit/02a9de5a5d279e71de202746678d0c6064a7a737  The new SLD file is at: https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/aggregated/TAXOUSDA.sld
