### ISSUE TITLE
Coordinates are not functioning properly

### ISSUE THREAD

**Issue by Flamingoo-Foods** [ISRICWorldSoil/SoilGrids250m#47]
It seems that the search for location function in the menu has a bug. If you type in a coordinate and check later under location (where all the entries of soilgrids are listed), the coordinates are not the same. Not sure what exactly is happening there. There is also the link for Openstreetmap and the location is shifted by a few kilometers. It would be also useful if you indicate what you have to type in eg. Lon/Lat (in decimals or is it degrees?!).  I think this is a quite big bug. Soilgrids has a high resolution but you cannot make use of it ifthe georeferencing is not working properly.
(Also it is a little bit awkward that lon and lat are switched in the 'search for location' entry and the menu at the top. Maybe this could be changed.)

**Comment by Flamingoo-Foods** [comment]
I also checked the app. Same problem exists there.

**Comment by ldesousa** [comment]
This seems to be an issue with the web application. Moved this issue to the correct repository.
