### ISSUE TITLE
Unknown soil mask 

### ISSUE THREAD

**Issue by tarasenkooleksii** [ISRICWorldSoil/SoilGrids250m#48]
In the window with description of type of soil, the message "Unknown soil mask" appears.
What do I have to do?

![image](https://user-images.githubusercontent.com/37071173/36973634-676324a8-207c-11e8-8c18-08931e422658.png)

**Comment by bkempen** [comment]
We have updated the query system. Issue should be solved. Query will return 'unknown soil mask' however if a non-soil pixel is queried (e.g. in a water body, built-up area).

**Comment by vjburton** [comment]
This issue is recurring again today. 'unknown soil mask' appears whatever location I choose.
