### ISSUE TITLE
No colours in Legend

### ISSUE THREAD

**Issue by mj-saunders** [ISRICWorldSoil/SoilGrids250m#49]
I am unable to see the legend colours when using soilgrids.org with my browser (don't have smart phone to test the app).
Numbers for the scale are loaded, but no colour swatches.
The map itself appears fine.

It appears no one else is having this issue from looking here and the mailing list.
It is the same on both a Linux and Windows machine that I'm running.

**Comment by bkempen** [comment]
Are you using firefox? There are some issues with displaying the legend using Firefox (I have it as well), which we cannot solve at short notice. In other browser the legend should appear.

**Comment by mj-saunders** [comment]
I am generally using Firefox. I'm sure I tested with other browsers, but apparently not.
Thank you very much, it is working nicely in a different browser.
