### ISSUE TITLE
SoilGrids250m : BDRICM_M  is not display in Geoserver

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#5]
The layer doesnt display and WMS request returns:

      Internal error occurred
All factories fail for the operation "ImageRead"java.lang.IllegalArgumentException: Source or destination region is empty.
Source or destination region is empty.

**Comment by thengl** [comment]
I will try to round up numbers (divide by 10) and then prepare this layer in Int16 format OK?

**Comment by jorgejesus** [comment]
problem related to the SLD
