### ISSUE TITLE
Problem to download 250m Soil grids by WCS

### ISSUE THREAD

**Issue by Ranfosic** [ISRICWorldSoil/SoilGrids250m#51]
Hello,

I would like to download Soils grid 250 m data by WCS on a territory of Algeria.  I use tutorial from "http://gsif.isric.org/doku.php/wiki:tutorial_soilgrids?do=export_pdf" but I can't access the server for WCS data.
Do you have a trouble to provide WCS datas?
R command error: 
system(paste(gdalinfo, xml.out))
ERROR 1: HTTP error code : 503
ERROR 1: Malformed Result:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2015 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>

Thanks for your response

Ranfosic

**Comment by ldesousa** [comment]
@Ranfosic The address of the WCS service in that page is incorrect. Please use instead: http://data.isric.org/geoserver/wcs?
