### ISSUE TITLE
Issue accessing FTP server

### ISSUE THREAD

**Issue by swood-ecology** [ISRICWorldSoil/SoilGrids250m#53]
I'm trying to access `ftp://ftp.soilgrids.org` on a Mac and I'm unable to access as a Guest. I tried finding a way to create an account on `isric.org` and I couldn't find anything. How can I create an account to access the FTP server?

![screen shot 2018-06-14 at 10 13 24 am](https://user-images.githubusercontent.com/16617156/41417615-dc0e916e-6fbb-11e8-9006-b96697523867.png)
![screen shot 2018-06-14 at 10 13 14 am](https://user-images.githubusercontent.com/16617156/41417616-dc1d38b8-6fbb-11e8-814a-b1e3652eafa6.png)
![screen shot 2018-06-14 at 10 13 07 am](https://user-images.githubusercontent.com/16617156/41417617-dc2cab18-6fbb-11e8-8c35-315d6d0a8da9.png)

**Comment by ldesousa** [comment]
@swood-ecology This is a public FTP, you should access it with "anonymous" for user name and password. Could you please detail what "share" exactly refers to in these dialogues?

**Comment by swood-ecology** [comment]
I tried to do this a different way, through Terminal. I still was asked to login with a USER and PASS:

```
CT201-SWOOD:~ stephen.wood$ ftp soilgrids.org
Connected to soilgrids.org.
220 (vsFTPd 3.0.3)
Name (soilgrids.org:stephen.wood): ls
530 This FTP server is anonymous only.
ftp: Login failed.
ftp> cd ..
530 Please login with USER and PASS.
ftp> quit
221 Goodbye.
```

**Comment by ldesousa** [comment]
@swood-ecology Here is an example:
```
$ ftp soilgrids.org
Connected to soilgrids.org.
220 (vsFTPd 3.0.3)
Name (soilgrids.org:duque004): anonymous
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
-rw-r--r--    1 0        0            2203 Apr 18  2017 README
drwxr-xr-x    7 0        0            4096 Mar 12 18:12 data
drwxr-xr-x    2 0        0            4096 Jul 28  2017 docs
drwxr-xr-x    3 0        0            4096 Jul 28  2017 legends
226 Directory send OK.
ftp> 

```

**Comment by ldesousa** [comment]
Closing, as this issue is unrelated to the models.
