### ISSUE TITLE
Extract averaged values for buffer around GPS locations?

### ISSUE THREAD

**Issue by thatrandomlurker** [ISRICWorldSoil/SoilGrids250m#56]
Hello,
I am wondering whether I can extract averaged values for a user-defined width around a spatial point (similar to the buffer argument in raster::extract()). I am using the rest.soilgrids.org query and would like to avoid having to download all .tif files just to be able to use the extract function of the raster package.

Best regards,
a fan

**Comment by ldesousa** [comment]
Hi there,
This kind of functionality is not available through the ReST API. However, if the area around the point is not too large, you can easily iterate through all the cells within it ans issue a query for each.
Regards.
