### ISSUE TITLE
Multiple SLD   have wrong NODATA values

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#6]
BLDFIE.sld  has no entrance for nodata 
NoData Value=-32768

it has Zero has no data

**Comment by jorgejesus** [comment]
Also CECSOL.sld

**Comment by jorgejesus** [comment]
CLYPPT.sld

**Comment by jorgejesus** [comment]
SLTPPT.sld

**Comment by thengl** [comment]
Now fixed in https://github.com/ISRICWorldSoil/SoilGrids250m/commit/02a9de5a5d279e71de202746678d0c6064a7a737
