### ISSUE TITLE
Missing XML for CECSUM

### ISSUE THREAD

**Issue by jorgejesus** [ISRICWorldSoil/SoilGrids250m#8]
Missing XML information for CECSUM

**Comment by thengl** [comment]
New name for the variable is "CECSOL" i.e. Cation exchange capacity of soil in cmolc/kg. CECSUM would indicate that we are providing the sum of CEC (https://en.wikipedia.org/wiki/Cation-exchange_capacity), which is not correct.

**Comment by thengl** [comment]
Remove all existing "CECSUM" from the server.

**Comment by thengl** [comment]
The SLD file for CECSOL is at: https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/aggregated/CECSOL.sld
